#!/bin/bash

### Provided by CI runner
#export CI_API_V4_URL='https://gitlab.com/api/v4'
#export CI_JOB_TOKEN=''  # NOTE lacks permissions
#export CI_PROJECT_PATH='mediaire/analytics/code-review'
#export CI_PROJECT_ID='30551020'
# TODO unfortunately not in our runner
#export CI_MERGE_REQUEST_IID='4'
###

### Provided by project CI variables
#export CI_PROJECT_TOKEN=''
###

# As the CI_JOB_TOKEN generated by the runner for this job session lacks the
# necessary permissions [https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html]
# to modify the MR notes and project variables, we need to use a project
# specific token.
#
# Generate a token as described here
# [https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html]
# and add a variable CI_PROJECT_TOKEN with the token as its value as shown in
# [https://docs.gitlab.com/ee/ci/variables/#add-a-cicd-variable-to-a-project].

CHECKLIST="\
Code Review Checklist
---------------------
_Please acknowledge that you checked all items by reacting to this note with
a :white_check_mark:_

- [ ] Be nice
- [ ] Find Bugs
"

VARIABLE_PREFIX=CI_CR_BOT_NOTE

note_found() {
	# check if a environment variable exists that indicates that this MR
	# already has a checklist
	curl \
		--header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
		--fail \
		--no-progress-meter \
		--request GET \
		"$CI_API_V4_URL/projects/$CI_PROJECT_ID/variables" \
	| grep "\"${VARIABLE_PREFIX}_${CI_MERGE_REQUEST_IID}\""
}

create_note() {
	# create the checklist
	curl \
		--header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
		--fail \
		--no-progress-meter \
		--request POST \
		"$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" \
		--data-urlencode "body=$CHECKLIST"

	# create a environment variable to indicate that this MR 
	curl \
		--header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
		--fail \
		--no-progress-meter \
		--request POST \
		"$CI_API_V4_URL/projects/$CI_PROJECT_ID/variables" \
		--data-urlencode "key=${VARIABLE_PREFIX}_${CI_MERGE_REQUEST_IID}" \
		--data-urlencode "value=true" \
		--data-urlencode "protected=false"
}


if note_found; then
	echo "Checklist already posted."
else
	echo "No checklist found. Creating one."
	echo
	echo "$CHECKLIST"
	echo
	create_note
fi

